name: flutterBoilerplate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  rxdart: ^0.24.1
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  image_picker: ^0.6.7+17
  modal_bottom_sheet: ^1.0.0+1
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.8.1
  auto_size_text: ^2.1.0
  introduction_screen: ^1.0.9

flutter_icons:
    android: true
    ios: true
    image_path: "assets/ic_launcher.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/


  